/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.sheeponthetable.gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;
import my.sheeponthetable.tools.User;
import my.sheeponthetable.tools.WebServiceClient;

/**
 *
 * @author Alex
 */
public class FarmTools extends javax.swing.JFrame {

    private SheepPanel sheepPanel;
    private List<User> users = new ArrayList();
    private DefaultListModel listModel = new DefaultListModel();
    private int farmID = Integer.parseInt(WebServiceClient.getFarmId());
    private ListSelectionListener userSelect;
    private User selectedUser;
    private boolean hasDoneChangesToSelectedUser = false; // used to determine if we should alert the user of unsaved changes
    private boolean dontShowConfirm = false; // so the popup doesnt come twice

    /**
     * Creates new form AddNewSheep
     */
    public FarmTools(SheepPanel sp, int id) {
        initComponents();

        this.setTitle("Preferences for " + WebServiceClient.getFarmName());

        ClearanceChoice.add("Owner");
        ClearanceChoice.add("Administrator");
        ClearanceChoice.add("View Access only");
        ClearanceChoice.select(2);
        setDisable();
        getUsers();
        refreshUserList();



    }

    /**
     * Disables input from the user
     */
    private void setDisable() {
        ClearanceChoice.setEnabled(false);
        cbxEmailAlertAttack.setEnabled(false);
        cbxSMSAlertAttack.setEnabled(false);
        cbxEmailAlertStationary.setEnabled(false);
        cbxSMSAlertStationary.setEnabled(false);
        cbxEmailAlertHealth.setEnabled(false);
        cbxSMSAlertHealth.setEnabled(false);
        btnSave.setEnabled(false);

    }

    /**
     * Enables input from user
     */
    private void setEnable() {
        cbxEmailAlertAttack.setEnabled(true);
        cbxSMSAlertAttack.setEnabled(true);
        cbxEmailAlertStationary.setEnabled(true);
        cbxSMSAlertStationary.setEnabled(true);
        cbxEmailAlertHealth.setEnabled(true);
        cbxSMSAlertHealth.setEnabled(true);
        btnSave.setEnabled(true);

    }

    /**
     * Sets the users variable with the user array from the WebService
     */
    private void getUsers() {

        if (WebServiceClient.getUsersForFarm(farmID) != null) {
            users = WebServiceClient.getUsersForFarm(farmID);
        } else {
            listModel.addElement("No users found.");
        }
    }

    /**
     * Populates the userlist
     */
    private void refreshUserList() {
        if (WebServiceClient.getUserLevel(farmID, Integer.parseInt(WebServiceClient.getUserId())) == 2) {

            for (User user : users) {
                listModel.addElement(user.getUsername());
            }
        } else {
            for (User user : users) {
                if (user.getUserId() == Integer.parseInt(WebServiceClient.getUserId)) {
                    listModel.addElement(user.getUsername());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jCheckBox9 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListUser = new javax.swing.JList();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblFarmName = new javax.swing.JLabel();
        lblUserNameListLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxEmailAlertAttack = new javax.swing.JCheckBox();
        cbxSMSAlertAttack = new javax.swing.JCheckBox();
        cbxEmailAlertHealth = new javax.swing.JCheckBox();
        cbxSMSAlertHealth = new javax.swing.JCheckBox();
        cbxSMSAlertStationary = new javax.swing.JCheckBox();
        cbxEmailAlertStationary = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        lblClerance = new javax.swing.JLabel();
        ClearanceChoice = new java.awt.Choice();
        lblName = new javax.swing.JLabel();
        lblSelectedUserName = new javax.swing.JLabel();
        lblFarmNameTxt = new javax.swing.JLabel();

        jCheckBox9.setText("jCheckBox9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jListUser.setModel(listModel);
        jListUser.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                FarmTools.this.valueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListUser);

        btnSave.setText("Save ");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblFarmName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFarmName.setText("Farm name:");

        lblUserNameListLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUserNameListLabel.setText("Username:");

        jLabel6.setText("Alert by E-mail:");

        cbxEmailAlertAttack.setText("Sheep killed");
        cbxEmailAlertAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSettingsChanged(evt);
            }
        });

        cbxSMSAlertAttack.setText("Sheep killed");

        cbxEmailAlertHealth.setText("Health");

        cbxSMSAlertHealth.setText("Health");

        cbxSMSAlertStationary.setText("Stationary");

        cbxEmailAlertStationary.setText("Stationary");

        jLabel7.setText("Alert by phone:");

        lblClerance.setText("Clearance:");

        ClearanceChoice.setName(""); // NOI18N

        lblName.setText("Name:");

        lblSelectedUserName.setText("            ");

        lblFarmNameTxt.setText("               ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserNameListLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cbxEmailAlertAttack)
                            .addComponent(cbxEmailAlertHealth)
                            .addComponent(cbxEmailAlertStationary)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cbxSMSAlertAttack)
                            .addComponent(cbxSMSAlertStationary)
                            .addComponent(cbxSMSAlertHealth)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClerance)
                            .addComponent(lblFarmName)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClearanceChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFarmNameTxt)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblSelectedUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFarmName)
                    .addComponent(lblUserNameListLabel)
                    .addComponent(lblFarmNameTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(lblSelectedUserName))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClerance)
                            .addComponent(ClearanceChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxEmailAlertAttack)
                            .addComponent(cbxSMSAlertAttack))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxEmailAlertHealth)
                            .addComponent(cbxSMSAlertHealth))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxSMSAlertStationary)
                            .addComponent(cbxEmailAlertStationary))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnCancel)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * Fires everytime a user clicks on a user in the list
     *
     * @param evt
     */
    private void valueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_valueChanged
        if (this.hasDoneChangesToSelectedUser && this.dontShowConfirm) {
            // make sure that the confirm button doesnt show up again if we press no or cancel
            this.dontShowConfirm = true;
            
            // show confirmation popup
            int confirm = JOptionPane.showConfirmDialog(null, "You have unsaved changes, are you sure you want to discard them?");

            // if user chooses no/cancel
            if (confirm != 0) {
                jListUser.setSelectedIndex(evt.getLastIndex());
                return;
            } else {
                // the user has discareded the changes
                this.hasDoneChangesToSelectedUser = false;
            }

        } else {
            this.dontShowConfirm = false;
        }

        if (jListUser.getSelectedIndex() != -1) {

            // If user is not a farm owner - (s)he can only change own info
            if (WebServiceClient.getUserLevel(farmID, Integer.parseInt(WebServiceClient.getUserId())) == 2) {
                this.selectedUser = users.get(jListUser.getSelectedIndex());
                ClearanceChoice.setEnabled(true); // owners can set levels
            } else {
                for (User user : users) {
                    if (user.getUserId() == Integer.parseInt(WebServiceClient.getUserId())) {
                        selectedUser = user;
                    }
                }
            }

            // enable input components
            setEnable();

            // set info
            lblSelectedUserName.setText(selectedUser.getName());
            ClearanceChoice.select(Math.abs(this.selectedUser.getClearance(this.farmID) - 2));

            cbxEmailAlertAttack.setSelected(selectedUser.getEmailAlarmAttack());
            cbxEmailAlertHealth.setSelected(selectedUser.getEmailAlarmHealth());
            cbxEmailAlertStationary.setSelected(selectedUser.getEmailAlarmStationary());

            cbxSMSAlertAttack.setSelected(selectedUser.getSMSAlarmAttack());
            cbxSMSAlertHealth.setSelected(selectedUser.getSMSAlarmHealth());
            cbxSMSAlertStationary.setSelected(selectedUser.getSMSAlarmStationary());

        }
    }//GEN-LAST:event_valueChanged

    private void userSettingsChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSettingsChanged
        
        
        this.hasDoneChangesToSelectedUser = true;

        selectedUser.setEmailAlarmAttack(cbxEmailAlertAttack.isSelected());
        selectedUser.setEmailAlarmHealth(cbxEmailAlertHealth.isSelected());
        selectedUser.setEmailAlarmStationary(cbxEmailAlertStationary.isSelected());

        selectedUser.setSMSAlarmAttack(cbxSMSAlertAttack.isSelected());
        selectedUser.setSMSAlarmHealth(cbxSMSAlertHealth.isSelected());
        selectedUser.setSMSAlarmStationary(cbxSMSAlertStationary.isSelected());

    }//GEN-LAST:event_userSettingsChanged

    /**
     * Triggered when the Save-button is clicked. Sends the selectedUser object to the WebServiceClient and saves the changes.
     * @param evt 
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       /* if(WebServiceClient.setUserPermissions(selectedUser)) {
            // success
            this.hadDoneChangesToSelectedUser = false;
        } else {
            JOptionPane.showMessageDialog(null, "Failed to save settings.");
        }
        */
    }//GEN-LAST:event_btnSaveActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice ClearanceChoice;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cbxEmailAlertAttack;
    private javax.swing.JCheckBox cbxEmailAlertHealth;
    private javax.swing.JCheckBox cbxEmailAlertStationary;
    private javax.swing.JCheckBox cbxSMSAlertAttack;
    private javax.swing.JCheckBox cbxSMSAlertHealth;
    private javax.swing.JCheckBox cbxSMSAlertStationary;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jListUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClerance;
    private javax.swing.JLabel lblFarmName;
    private javax.swing.JLabel lblFarmNameTxt;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSelectedUserName;
    private javax.swing.JLabel lblUserNameListLabel;
    // End of variables declaration//GEN-END:variables
}
